version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
  api:
    build:
      context: .
      dockerfile: Tyt-api-dockerfile
    restart: always
    ports:
      - 8443:8443
  web:
    build:
      context: .
      dockerfile: Tyt-web-dockerfile
    restart: always
    ports:
      - 8081:8081